game:
  type: leduc
  num_players: 2
  showdown_street: showdown
  legal_raise_pot_size: []
  num_runs: 20
  initial_chips: 100
  payoff_max: 15
  circular_train: false
  custom_board_cards: null
  num_action: 5

resources:
  num_cpus: 64
  num_gpus: 4

rllib:
  num_rollout_workers: 16
  num_envs_per_worker: 4
  num_cpus_per_worker: 0.125
  num_gpus_per_worker: 0.1
  num_gpus_algorithm: 0.5
  num_learner_workers: 0
  framework: torch
  log_level: ERROR
  evaluation_interval: 1
  verbose: 2

hyper:
  model: hunl_conv
  learning_rate: 0.00005
  clip_param: 0.2
  entropy_coeff: 0.01
  train_batch_size: 8192
  sgd_minibatch_size: 256
  num_sgd_iter: 30
  kl_coeff: 0.2
  kl_target: 0.003
  vf_clip_param: 10.0
  vf_loss_coeff: 1.0
  opponent_count: 4
  num_update_iter: 20
  win_rate_threshold: 100
  checkpoint_frequency: 10
  checkpoint_num_to_keep: 10
  stop_timesteps_total: 2000000000
  stop_training_iteration: 400000

self_play:
  type: leduc
  opponent_policies: [random]
  num_opponent_limit: 1
  num_update_iter: 20
  win_rate_window_size: 6
  arena_runs: 2048

policy:
  alphaholdem: /home/clouduser/zcc/Holdem/checkpoint/38000_model/model.ckpt
  leduc_cfr: /home/clouduser/zcc/Holdem/strategy/leduc.txt