game:
  type: range_kuhn
  num_players: 2
  showdown_street: flop
  legal_raise_pot_size: []
  num_runs: 1
  initial_chips: 4
  payoff_max: 2
  circular_train: false
  custom_board_cards: null
  num_action: 4

resources:
  num_cpus: 64
  num_gpus: 4

rllib:
  num_rollout_workers: 16
  num_envs_per_worker: 4
  num_cpus_per_worker: 0.125
  num_gpus_per_worker: 0.1
  num_gpus_algorithm: 0.5
  num_learner_workers: 0
  framework: torch
  log_level: ERROR
  evaluation_interval: 1
  verbose: 2

hyper:
  model: range_kuhn
  learning_rate: 0.00005
  clip_param: 0.2
  entropy_coeff: 0.01
  train_batch_size: 1024
  sgd_minibatch_size: 128
  num_sgd_iter: 30
  kl_coeff: 0.2
  kl_target: 0.003
  vf_clip_param: 10.0
  vf_loss_coeff: 1.0
  num_update_iter: 20
  win_rate_threshold: 100
  checkpoint_frequency: 10
  checkpoint_num_to_keep: 10
  stop_timesteps_total: 2000000000
  stop_training_iteration: 400000

self_play:
  type: naive
  arena: kuhn
  policy_type: range_kuhn
  rule_based_policies: []
  num_opponent_limit: 1
  num_update_iter: 5000
  arena_runs: 16384

policy:
  alphaholdem: /home/clouduser/zcc/Holdem/checkpoint/38000_model/model.ckpt
  leduc_nash: /home/clouduser/zcc/Holdem/strategy/leduc_nash.txt
  kuhn_nash: /home/clouduser/zcc/Holdem/strategy/kuhn_nash.txt