game:
  type: range_leduc
  num_players: 2
  showdown_street: turn
  legal_raise_pot_size: []
  num_runs: 20
  initial_chips: 100
  payoff_max: 100
  circular_train: false
  custom_board_cards: null
  num_action: 4

resources:
  num_cpus: 64
  num_gpus: 4

rllib:
  num_rollout_workers: 16
  num_envs_per_worker: 4
  num_cpus_per_worker: 0.125
  num_gpus_per_worker: 0.1
  num_gpus_algorithm: 0.5
  num_learner_workers: 0
  framework: torch
  log_level: ERROR
  evaluation_interval: 1
  verbose: 2

hyper:
  model: range_leduc
  learning_rate: 0.0001
  clip_param: 0.2
  entropy_coeff: 0.0
  train_batch_size: 16384
  sgd_minibatch_size: 256
  num_sgd_iter: 30
  kl_coeff: 0.2
  kl_target: 0.0025
  vf_clip_param: 10.0
  vf_loss_coeff: 1.0
  opponent_count: 4
  num_update_iter: 20
  win_rate_threshold: 100
  checkpoint_frequency: 20
  checkpoint_num_to_keep: 5
  stop_timesteps_total: 2000000000
  stop_training_iteration: 400000

self_play:
  type: naive
  arena: leduc
  policy_type: range_leduc
  rule_based_policies: [range_leduc_cfr]
  num_opponent_limit: 5
  num_update_iter: 10000000
  arena_runs: 2048

policy:
  alphaholdem: /home/clouduser/zcc/Holdem/checkpoint/38000_model/model.ckpt
  leduc_nash: /home/clouduser/zcc/Holdem/strategy/leduc_nash.txt
  kuhn_nash: /home/clouduser/zcc/Holdem/strategy/kuhn_nash.txt